eureka:
  client:
    service-url:
      defaultZone: http://localhost:18000/eureka/

logging:
  level:
    ROOT: info
    org:
      springframework:
        jdbc:
          core: TRACE

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
