eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18000/eureka/

logging:
  level:
    ROOT: info

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
