server:
  port: 18001

spring:
  application:
    name: background-server
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES # 请求参数下划线转驼峰命名
  profiles:
    active: dev
  rabbitmq:
    listener:
      simple:
        prefetch: 1 # 每个消费者可能未完成的最大未确认消息数量
  task:
    execution:
      shutdown:
        await-termination: true # 应用关闭时，是否等待定时任务执行完成
#      thread-name-prefix: task-

info:
  app:
    name: ${spring.application.name}
    port: ${server.port}
    active: ${spring.profiles.active}
    eruaka-zone: ${eureka.client.service-url.default-zone}
    java: ${java.version}