server:
  port: 18000

spring:
  application:
    name: eureka-server
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: dev
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost

info:
  app:
    name: ${spring.application.name}
    port: ${server.port}
    active: ${spring.profiles.active}
    hostname: ${eureka.instance.hostname}
    eureka-zone: ${eureka.client.service-url.default-zone}
    java: ${java.version}